name: CI
on:
  - push
  - pull_request
permissions:
  contents: read
jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 22
          - 26 # Node.js 26 support Uint8Array.fromBase64()
          - latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - uses: codecov/codecov-action@v5
        with:
          name: Node.js ${{ matrix.node-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
